Repository Cha-Young-Ho/TogetherSports, pull requests merged in 2022-03, with the labels that each got.

#61 Feature : 유저 정보 수정 구현
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/MyInfoController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserDTO.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
  backend/tos-proejct/src/main/resources/application.yml
Labels: enhancement

#68 Feature : User-Agent에 따른 Refresh 저장 구현
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/TestController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/RefreshToken.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/RefreshTokenRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserDTO.java
Labels: enhancement

#69 Feature : cors 설정 완료
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/config/SecurityConfig.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/exception/ErrorControllerAdvice.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/response/ErrorResponse.java
Labels: bug

#70 Feature: Response 메세지 기능 구현 #1
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/code/Code.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/config/SecurityConfig.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/exception/CustomAuthenticationEntryPoint.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/exception/ErrorControllerAdvice.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtAuthenticationFilter.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtExceptionFilter.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/response/ErrorResponse.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/Car.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
Labels: enhancement

#73 BugFix : Message 처리 시, JWT 인증 무조건 통과 현상 해결
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/exception/CustomAuthenticationEntryPoint.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/exception/CustomSignatureException.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/exception/ErrorControllerAdvice.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtAuthenticationFilter.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtExceptionFilter.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtTokenProvider.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/MyInfoController.java
Labels: bug

#76 Feature : 다른 회원 정보 조회 기능 구현
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/response/OtherInfoResponse.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/OtherInfoController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/OtherUserDTO.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
Labels: enhancement

#100 BugFix : 각종 에러 수정#2
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/enums/Gender.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/enums/Provider.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/file/FileHandler.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserDTO.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/userProfileImage/UserProfileImage.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/userProfileImage/UserProfileImageDTO.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/userProfileImage/UserProfileImageService.java
  backend/tos-proejct/src/test/java/com/togethersports/tosproejct/login/LoginTest.java
Labels: enhancement

#103 Feature : Room Create 완료
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/controller/RoomCRUDController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/fields/RoomArea.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/fields/RoomImage.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/module/RoomFileHandler.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/repository/RoomAreaRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/repository/RoomImageRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/repository/RoomTagRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/roomDTO/RoomCreateDTO.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/roomDTO/RoomImageDTO.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/service/RoomCRUDService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/service/RoomService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
Labels: enhancement

#116 Feature : logout 구현
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/config/SecurityConfig.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtExceptionFilter.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/jwt/JwtTokenProvider.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
Labels: enhancement

#162 Feature : Refresh 생성, 발급, 저장 #1
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/Account.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/AccountRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/SecurityConfig.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/JwtProperties.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/dto/TokenOfLogin.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtAuthenticationFilter.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtRefreshFilter.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/token/RefreshToken.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtDecoder.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtTokenFactory.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/CustomOAuth2User.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/handler/OAuth2LoginAuthenticationSuccessHandler.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/service/CustomOAuth2UserService.java
  backend/tos-proejct/src/main/resources/application-jwt.yml
Labels: 기능구현

#164 Feature : renew accessToken 작업완료
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/CommonCode.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/SecurityConfig.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtAuthenticationFilter.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtRefreshFilter.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/provider/JwtAuthenticationProvider.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/token/RefreshToken.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtDecoder.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtTokenFactory.java
Labels: 기능구현

#172 Feature : Refresh Token DB 중복 방지기능 구현완료
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtRefreshFilter.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/token/RefreshToken.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/handler/OAuth2LoginAuthenticationSuccessHandler.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/util/ClientIpUtils.java
Labels: 기능구현

#175 Feature : Cors 세팅
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/SecurityConfig.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtAuthenticationFilter.java
Labels: 기능구현

#188 Feature : 방 이미지 등록 구현
  frontend/components/navigationBar.js
  frontend/pages/room/createroom/roomtaginfo.js
  frontend/pages/signup/addinfo/personalinfo.js
  frontend/store/rootReducer.js
Labels: 기능구현

#191 Feature : Logout 구현 완료
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/code/CommonCode.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/SecurityConfig.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/handler/CustomLogoutHandler.java
Labels: 기능구현

#195 Feature : 닉네임 중복확인 구현완료
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/code/UserCode.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/CustomOAuth2User.java
Labels: 기능구현

#198 Feature : 다른 회원 정보 조회 기틀 마련
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfOtherInfo.java
Labels: 기능구현

#199 Refactoring : 매핑 변경 및 로직 변경(ActiveArea, Interests)
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/User.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/area/ActiveArea.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/util/ParsingEntityUtils.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/interest/Interest.java
  backend/tos-proejct/src/main/resources/application.yml
Labels: 리팩토링

#202 Feature : 다른 회원 정보 조회 및 리프레시 관련 예외 처리
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/User.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/code/UserCode.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfOtherInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/controller/ExceptionControllerAdvice.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/util/ParsingEntityUtils.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/SecurityConfig.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/JwtErrorCode.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtRefreshFilter.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/handler/JwtRefreshTokenExceptionHandler.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtDecoder.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtTokenFactory.java
Labels: 기능구현

#204 Feature : 회원 정보 수정 틀 마련
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/User.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfModifyInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/exception/NicknameDuplicationException.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/controller/ExceptionControllerAdvice.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/handler/JwtRefreshTokenExceptionHandler.java
Labels: 기능구현

#209 Feature : 내 정보 조회, 로그아웃 리팩토링
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfMyInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/controller/ExceptionControllerAdvice.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/SecurityConfig.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/handler/CustomLogoutHandler.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/handler/JwtRefreshTokenExceptionHandler.java
Labels: 기능필요, 리팩토링

#210 Feature : 내 정보 조회 수정
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfInitInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfModifyInfo.java
Labels: 기능필요

#211 Feature : nav바 요청 완료 및 다른 회원 정보 조회 로직 변경
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfMyInfoSummary.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/handler/OAuth2LoginAuthenticationSuccessHandler.java
Labels: 기능구현, 리팩토링
