Repository Cha-Young-Ho/TogetherSports, pull requests merged in 2022-04, with the labels that each got.

#215 기타 로직 수정
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/code/UserCode.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfMyInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfOtherInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/exception/NicknameDuplicationException.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/exception/NotEnteredInformationException.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/controller/ExceptionControllerAdvice.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtTokenFactory.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/handler/OAuth2LoginAuthenticationSuccessHandler.java
  backend/tos-proejct/src/main/resources/application-oauth2.yml
Labels: 리팩토링

#221 Feature : 이미지 대표사진 기능 구현
  frontend/components/rooms/setRoomImages.js
  frontend/pages/room/createroom/roomtaginfo.js
Labels: 기능구현

#224 Feature : api 수정에 따른 코드수정
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfMyInfoSummary.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/account/dto/UserOfOtherInfo.java
Labels: 리팩토링

#228 Feature : Room 도메인 작성 및 관련 도메인 작성
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/area/ActiveArea.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/controller/ExceptionControllerAdvice.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/util/ParsingEntityUtils.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImage.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/interest/Interest.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/ImageOfRoomCreate.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfCreate.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/RefreshTokenService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/provider/JwtAuthenticationProvider.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/token/JwtPostAuthenticationToken.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtDecoder.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtTokenFactory.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/CustomOAuth2User.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/handler/OAuth2LoginAuthenticationSuccessHandler.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/service/CustomOAuth2UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/tag/Tag.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/tag/TagRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/tag/TagService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/Gender.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/code/UserCode.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/dto/UserOfInitInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/dto/UserOfModifyInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/dto/UserOfMyInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/dto/UserOfOtherInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/exception/NicknameDuplicationException.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/exception/NotEnteredInformationException.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/exception/UserNotFoundException.java
Labels: 기능구현

#232 Refactoring : 회원 파트 리팩토링 구현
  frontend/api/members.js
  frontend/components/login.js
  frontend/components/navigationBar.js
  frontend/components/roomInfoNavBar.js
  frontend/components/userInfoNavBar.js
  frontend/pages/signup/addinfo/activearea.js
  frontend/pages/signup/addinfo/personalinfo.js
  frontend/pages/usermodification.js
Labels: 리팩토링

#240 [Feature Request] Room Create ver1 완료
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/area/ActiveArea.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/controller/ExceptionControllerAdvice.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/util/ParsingEntityUtils.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImage.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImageRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImageService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/ImageOfRoomCreate.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfCreate.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/SecurityConfig.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/tag/Tag.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/tag/TagService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
Labels: 기능구현

#242 Feature : 방 조회 완료#1
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/controller/ExceptionControllerAdvice.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/util/ParsingEntityUtils.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/code/RoomCode.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/ImageOfRoomInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfCreate.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/exception/NotFoundRoomException.java
Labels: 기능구현

#246 Feature : 방 수정 구현 완료#1
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImage.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImageRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImageService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/ImageOfRoomCRUD.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfCreate.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfUpdate.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/tag/Tag.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/tag/TagRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/tag/TagService.java
Labels: 기능구현

#247 Feature: Login과정 수정 및 추가정보 입력 과정 수정
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/handler/OAuth2LoginAuthenticationSuccessHandler.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/service/CustomOAuth2UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/dto/UserOfInitInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/dto/UserOfModifyInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/dto/UserOfMyInfo.java
Labels: 리팩토링

#250 Feature : 기타 api 관련 로직 수정
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfCreate.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfUpdate.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/util/JwtTokenFactory.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/service/CustomOAuth2UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/User.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/dto/UserOfMyInfo.java
Labels: 문서수정, 리팩토링

#273 Feature : 필터링 작업 완료
  backend/tos-proejct/build.gradle
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/config/QuerydslConfig.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepositoryCustom.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepositoryImpl.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/FieldsOfRoomList.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfList.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomsOfListInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/config/SecurityConfig.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/Gender.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/dto/UserOfMyInfo.java
Labels: 기능구현

#275 Feature : Room Auditing 기능 추가
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/TosProjectApplication.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/auditing/RoomBaseEntity.java
Labels: 기능구현

#276 Feature : 방 정렬 기능 추가
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepositoryImpl.java
Labels: 기능구현

#281 Feature : Tag 수정
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/Room.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepositoryImpl.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/tag/Tag.java
  backend/tos-proejct/src/main/resources/application.yml
Labels: 기능구현

#291 Feature : 방 수정사항 반영#2
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepositoryCustom.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepositoryImpl.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfList.java
Labels: 기능구현

#300 Feature : 주석추가
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImageService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepositoryImpl.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/auditing/RoomBaseEntity.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/FieldsOfRoomList.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/ImageOfRoomInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfList.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfUpdate.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomsOfListInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/config/SecurityConfig.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserController.java
  backend/tos-proejct/src/main/resources/application-storage.yml
  backend/tos-proejct/src/main/resources/application.yml
Labels: 리팩토링

#301 Feature : 이미지 기본 경로 변경 및 fetch 조인 적용
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/image/RoomImageService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomRepositoryImpl.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/oauth2/handler/OAuth2LoginAuthenticationSuccessHandler.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
  backend/tos-proejct/src/main/resources/application.yml
Labels: 리팩토링

#318 Feature : 회의에 따른 수정사항 반영
  backend/tos-proejct/build.gradle
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatMessage.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatRepository.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/auditing/ChatBaseEntity.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/dto/ChatOfMessage.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/dto/ChatOfPubRoom.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/dto/ChatOfReceiveRoom.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/dto/SampleMessage.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/handler/ChatPreHandler.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/config/SocketConfig.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/code/RoomCode.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/FieldsOfRoomList.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtRefreshFilter.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
  backend/tos-proejct/src/main/resources/application.yml
Labels: bounded: backend

#331 Feature : Attandance 구현
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/chat/ChatService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/common/controller/ExceptionControllerAdvice.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/participant/ParticipantService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomController.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/RoomService.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/room/dto/RoomOfInfo.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/security/jwt/filter/JwtAuthenticationFilter.java
  backend/tos-proejct/src/main/java/com/togethersports/tosproejct/user/UserService.java
  backend/tos-proejct/src/main/resources/application.yml
Labels: type: 🔨feature
